### ISSUE TITLE
How to configure Openvswith pod network ?

### ISSUE THREAD

**Issue by ikus060** [nak3/openshift-manual-install#1]
Hello,

I'm trying to install openshift manually. I mostly did the same as you. But I still don't understand how to configure the pod network. I want to use osv-subnet (as a start). I understand I must define the right value for networkPluginName, but it doesn't work...
```
master has not created a default cluster network, network plugin "redhat/openshift-ovs-subnet" can not start
```

**Comment by nak3** [comment]
Hi,

Unfortunately, this manual installation guide has not been maintained since 3.0. I believe that this manual step cannot work on recent version.

Although I wanted to maintain this steps, OpenShift installation has a lot of changes among minor version up and this patch https://github.com/openshift/origin/pull/4760 hasn't accepted, so I stopped maintaining this repository.

I would appreciate it if you could use ansible installation and if you saw any issue, report it to the ansible repo.

**Comment by ikus060** [comment]
Yep, the steps changed allot since 3.0. I'm working on a manual installation to learn how stuff is working. And I'm stuck with the pod network. In kubernetes I would simply load the yaml for flannel or calico, but I did not find such a thing for openshift. Was hoping you could help me...

Thanks for your reply

**Comment by nak3** [comment]
I see. If you like, could you please try to reach out community ML http://lists.openshift.redhat.com/openshiftmm/listinfo ?

Also, probably sharing networkConfig in master-config.yaml (following parts) with them could help for the troubleshooting.

- /etc/origin/master/master-config.yaml
~~~
... snip ...
networkConfig:
  clusterNetworkCIDR: 10.128.0.0/14
  hostSubnetLength: 9
  networkPluginName: redhat/openshift-ovs-subnet
# serviceNetworkCIDR must match kubernetesMasterConfig.servicesSubnet
  serviceNetworkCIDR: 172.30.0.0/16
  externalIPNetworkCIDRs:
  - 0.0.0.0/0
~~~

**Comment by nak3** [comment]
I'm closing this per [this ML](http://lists.openshift.redhat.com/openshift-archives/users/2017-November/msg00109.html)
